CREATE TABLE IF NOT EXISTS PUBLIC."Genre" (
	GENRE_ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(100) NOT NULL,
	CONSTRAINT PK_GENRE PRIMARY KEY (GENRE_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC."Rating" (
	RATING_ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(50) NOT NULL,
	CONSTRAINT PK_RATING PRIMARY KEY (RATING_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC."Users" (
	USER_ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(255) NOT NULL,
	LOGIN CHARACTER VARYING(100) NOT NULL,
	EMAIL CHARACTER VARYING(255) NOT NULL,
	BIRTHDAY DATE NOT NULL,
	CONSTRAINT PK_USER PRIMARY KEY (USER_ID)
);

CREATE TABLE IF NOT EXISTS PUBLIC."Film" (
	FILM_ID INTEGER NOT NULL AUTO_INCREMENT,
	NAME CHARACTER VARYING(255) NOT NULL,
	DESCRIPTION CHARACTER LARGE OBJECT NOT NULL,
	RELEASE_DATE DATE NOT NULL,
	DURATION INTEGER NOT NULL,
	RATING_ID INTEGER NOT NULL,
	CONSTRAINT PK_FILM PRIMARY KEY (FILM_ID),
	CONSTRAINT FK_FILM_RATING_ID FOREIGN KEY (RATING_ID) REFERENCES PUBLIC."Rating"(RATING_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS PUBLIC."Film_genre" (
	FILM_ID INTEGER NOT NULL,
	GENRE_ID INTEGER NOT NULL,
	CONSTRAINT FK_FILM_GENRE_FILM_ID FOREIGN KEY (FILM_ID) REFERENCES PUBLIC."Film"(FILM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FK_FILM_GENRE_GENRE_ID FOREIGN KEY (GENRE_ID) REFERENCES PUBLIC."Genre"(GENRE_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS PUBLIC."Likes" (
	FILM_ID INTEGER NOT NULL,
	USER_ID INTEGER NOT NULL,
	CONSTRAINT FK_LIKES_FILM_ID FOREIGN KEY (FILM_ID) REFERENCES PUBLIC."Film"(FILM_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FK_LIKES_USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC."Users"(USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);

CREATE TABLE IF NOT EXISTS PUBLIC."User_friends" (
	USER_ID INTEGER NOT NULL,
	FRIEND_ID INTEGER NOT NULL,
	STATUS INTEGER NOT NULL,
	CONSTRAINT FK_USER_FRIENDS_FRIEND_ID FOREIGN KEY (FRIEND_ID) REFERENCES PUBLIC."Users"(USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT,
	CONSTRAINT FK_USER_FRIENDS_USER_ID FOREIGN KEY (USER_ID) REFERENCES PUBLIC."Users"(USER_ID) ON DELETE RESTRICT ON UPDATE RESTRICT
);