CREATE TABLE IF NOT EXISTS genres (
	genre_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS mpa (
	mpa_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name CHARACTER VARYING(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS users (
	user_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name CHARACTER VARYING(255) NOT NULL,
	login CHARACTER VARYING(100) NOT NULL,
	email CHARACTER VARYING(255) NOT NULL,
	birthday DATE NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
	film_id INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	name CHARACTER VARYING(255) NOT NULL,
	description TEXT NOT NULL,
	release_date DATE NOT NULL,
	duration INTEGER NOT NULL,
	mpa_id INTEGER NOT NULL,
	FOREIGN KEY (mpa_id) REFERENCES mpa (mpa_id) ON DELETE SET NULL
);

CREATE TABLE IF NOT EXISTS films_genres (
	film_id INTEGER,
	genre_id INTEGER,
	FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE,
	FOREIGN KEY (genre_id) REFERENCES genres (genre_id) ON DELETE CASCADE,
	PRIMARY KEY (film_id, genre_id)
);

CREATE TABLE IF NOT EXISTS likes (
	film_id INTEGER NOT NULL,
	user_id INTEGER NOT NULL,
	FOREIGN KEY (film_id) REFERENCES films (film_id) ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
	PRIMARY KEY (film_id, user_id)
);

CREATE TABLE IF NOT EXISTS user_friends (
	user_id INTEGER NOT NULL,
	friend_id INTEGER NOT NULL,
	FOREIGN KEY (friend_id) REFERENCES users (user_id) ON DELETE CASCADE,
	FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE CASCADE,
	PRIMARY KEY (user_id, friend_id)
);